### ISSUE TITLE
Benchmark_models.ipynb: Some functions using global variables in the notebook. Can't import them in BenchmarkModels.py

### ISSUE THREAD

**Issue by nskazmi** [prio-data/prediction_competition_2023#13]
![image](https://github.com/prio-data/prediction_competition_2023/assets/142994595/dd760fb9-392a-404c-996b-9a2f549b9c04)
![image](https://github.com/prio-data/prediction_competition_2023/assets/142994595/73021255-71be-4bf8-9577-c1a6b1160582)
![image](https://github.com/prio-data/prediction_competition_2023/assets/142994595/4270c24a-f0dc-42a8-ad3b-f8d355a64469)

**Comment by kvelleby** [comment]
benchmark code moved out of repository
