### ISSUE TITLE
from_table argument in Queryset .with_column

### ISSUE THREAD

**Issue by nskazmi** [prio-data/prediction_competition_2023#14]
![image](https://github.com/prio-data/prediction_competition_2023/assets/142994595/83080468-63ff-47aa-8b30-63bac408a968)

**'from_loa' works instead of 'from_table'

**Comment by nskazmi** [comment]
this issue is because of running viewser version > 6, downgrade to 5.14.1 and check.

**Comment by kvelleby** [comment]
benchmark code moved out of repository
