### ISSUE TITLE
To produce 'outcome' instead of 'ged-sb' in the output parquet files

### ISSUE THREAD

**Issue by nskazmi** [prio-data/prediction_competition_2023#15]
Change save_actuals() function in the BenchmarkModels.py 

use actuals['outcome'] instead of actuals['ged_sb']

![image](https://github.com/prio-data/prediction_competition_2023/assets/142994595/7027137c-681b-49b0-a1e9-e5a2cdc0b092)

**Comment by kvelleby** [comment]
benchmark code moved out of repository
