### ISSUE TITLE
Better visualizations

### ISSUE THREAD

**Issue by kvelleby** [prio-data/prediction_competition_2023#22]
We need to provide better visualizations out of the box.

Currently, we have implemented (but not merged with main-branch):
 - choropleth maps of country-level performance
 - ribbon plots to compare models and actuals for specific unit-ids over time

We have tables for global mean performance and by-window mean performance. We could also add plots for mean performance per month. We could also make plots out of these tables. To get performance per month and unit we will need to update how metrics are calculated (`xskillscore.crps_ensemble` force you to take the mean across some dimension. We would need to add a unique unit-month id and aggregate across that.)

Suggestions for visualizations come much appreciated! :)

**Comment by paolavesco** [comment]
One option is to use alpha levels to plot uncertainty on a map, as in here: https://nhess.copernicus.org/articles/22/1499/2022/#&gid=1&pid=1 especially Figure 3. I am exploring this with Xiaolong.

**Comment by hhegre** [comment]
Maybe tables should be a separate issue? We have to sort out the use of decimals. The standard in VIEWS (and at PRIO) is to use point as decimal, not comma, that must be changed. For thousand separator we use either space or comma, never point.

**Comment by hhegre** [comment]
I think @paolavesco 's idea for uncertainty maps is excellent. Maybe we have to present the uncertainty in terms of percentage of the prediction to make it comparable?

Another idea is to plot a histogram of the draws for a specific observation, to compare how uncertain models are for a given case.

**Comment by kvelleby** [comment]
The histogram for a specific observation is almost what we have done with `plotting.ribbon_plot()`, only that is is across time, and only showing 3 percentiles (low, mid, high). Of course, there might be a value to choosing only one observation-point to plot the full histogram. Again, I think using [Bayesian blocks](https://docs.astropy.org/en/stable/api/astropy.stats.bayesian_blocks.html) to define the binning would work nicely here.
